# Generated by Django 2.2 on 2020-11-27 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201127_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 12, 46, 910791, tzinfo=utc)),
        ),
    ]
