# Generated by Django 2.2 on 2020-11-28 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201128_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 15, 16, 39, 933616, tzinfo=utc)),
        ),
    ]
