# Generated by Django 2.2 on 2020-12-05 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201205_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 12, 37, 3, 346802, tzinfo=utc)),
        ),
    ]
