# Generated by Django 2.2 on 2020-12-05 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201205_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 12, 45, 55, 120916, tzinfo=utc)),
        ),
    ]
