# Generated by Django 2.2 on 2020-12-05 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201205_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 13, 22, 19, 293916, tzinfo=utc)),
        ),
    ]
