# Generated by Django 2.2 on 2020-12-05 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201205_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 14, 53, 3, 538384, tzinfo=utc)),
        ),
    ]
